-- First enable necessary extensions
create extension if not exists "uuid-ossp";
create extension if not exists vector;

-- Create documents table for vector store
create table if not exists documents (
    id bigint generated by default as identity primary key,
    content text,
    metadata jsonb,
    embedding vector(1536)
);

-- Create match_documents function with explicit table references
create or replace function match_documents (
    query_embedding vector(1536),
    match_count int default 5
) returns table (
    id bigint,
    content text,
    metadata jsonb,
    similarity float
)
language plpgsql
as $$
begin
    return query
    select
        documents.id,
        documents.content,
        documents.metadata,
        1 - (documents.embedding <=> query_embedding) as similarity
    from documents
    order by documents.embedding <=> query_embedding
    limit match_count;
end;
$$;